### ISSUE TITLE
permit/forbid_mass_assignment_of matchers seem a bit useless

### ISSUE THREAD

**Issue by mybaldbird** [chrisalley/pundit-matchers#29]
There are several issues with the permit/forbid_mass_assignment_of matchers.
1. As new attributes are added to permitted attributes, permit_mass_assignment_of will continue to pass.
2. Since everything that isn't permitted is explicitly forbidden, forbid_mass_assignment seems illogical. It isn't specific attributes you should care about being forbidden, the only thing that matters is what the permitted attributes actually are.
3. Can't use these matchers to test if permitted attributes is empty.

Let's say we have this policy:
```
class PostPolicy < ApplicationPolicy
  def permitted_attributes
    if user.admin?
      [:title, :content]
    else
      []
    end
  end
end
```

You're test case will look something like this:
```
RSpec.describe PostPolicy do
  subject { described_class.new(user, post) }
  let(:user) { create(:user) }
  let(:post) { build(:post) }
  context "as a user" do
    it { is_expected.to forbid_mass_assignment_of([:title, :content]) }
  end
  context "as an admin" do
    let(:user) { create(:user, :admin) }
    it { is_expected.to permit_mass_assignment_of([:title, :content]) }
  end
end
```
Say we add `:flair` to the permitted attributes in PostPolicy. All the tests still pass. Compare this with doing the test like this:
```
RSpec.describe PostPolicy do
  subject { described_class.new(user, post) }
  let(:user) { create(:user) }
  let(:post) { build(:post) }
  context "as a user" do
    it "permits the correct attributes" do
      expect(subject.permitted_attributes).to eq([])
   end
  end
  context "as an admin" do
    let(:user) { create(:user, :admin) }
    it "permits the correct attributes" do
      expect(subject.permitted_attributes).to contain_exactly(:title, :content)
   end
  end
end
```
With this test, the new code will cause the test to fail, making it obvious that the functionality of the policy has changed.

**Comment by chrisalley** [comment]
I appear be coming at this from a different angle to you. In my use cases I have been testing for very specific attributes being permitted or forbidden under different user contexts, rather than testing for an exact set of attributes being permitted or forbidden.

For better or worse, this approach is less comprehensive, instead focusing on what is most important to test from a security standpoint. If a particular field is always permitted under every user context (that also has permission to modify the record) then I may not need to test whether it is permitted if there are other tests that check to see if the record can be updated. Over-testing can potentially obscure what is important from the security standpoint.

> Since everything that isn't permitted is explicitly forbidden, forbid_mass_assignment seems illogical.

An attribute may only be forbidden under one user context, while being permitted under another. Being able to explicitly check that an attribute called publish is forbidden under a visitor user context and permitted under an author user context is useful.

That said, it may be worth adding some examples to the readme for testing that an exact set of attributes are permitted even if this is outside the scope of Pundit Matchers. If you are interesting in doing this, please create a PR.
